name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn --ignore-engines
    - name: Run ESLint
      run: yarn run eslint --ext .js
    - name: Run Backend tests
      run: yarn test
    - name: Install Frontend modules
      working-directory: ./client
      run: yarn --ignore-engines
    - name: Run Frontend tests
      working-directory: ./client
      run: yarn test
